import "../styles/FooterLink.css";
const TermsOfService = () => {
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
      <section>
        <h2 className="text-2xl font-semibold mb-2">1. Acceptance of Terms</h2>
        <p>By accessing or using our AI-powered services, you agree to be bound by these Terms of Service. Our services include AI-driven data analysis, machine learning model interactions, and related functionalities.</p>
      </section>
      <section>
        <h2 className="text-2xl font-semibold mb-2">2. Use of AI Services</h2>
        <p>You may use our AI services for lawful purposes only. You are responsible for ensuring that any data you input into our AI systems complies with applicable laws and does not infringe on third-party rights.</p>
      </section>
      <section>
        <h2 className="text-2xl font-semibold mb-2">3. Intellectual Property</h2>
        <p>All AI models, algorithms, and outputs generated by our services remain our property. You are granted a non-exclusive license to use the outputs for your personal or business purposes, subject to these terms.</p>
      </section>
    </div>
  );
};

export default TermsOfService;